### ISSUE TITLE
NuclearJS docs 404

### ISSUE THREAD

**Issue by bhamodi** [optimizely/nuclear-js#101]
Hey @jordangarcia, it seems that our new dev site did cause our docs to not load anymore. We'll have to look into what caused this.
It was first reported in #96 by https://github.com/citelao.

**Comment by citelao** [comment]
:+1:

**Comment by jordangarcia** [comment]
Ah yes Optimizely switched the developers site repo.

Nuclear docs will live at https://optimizely.github.io/nuclear-js from now on.

I will be adding a page on the developer site to notify people that they have moved.

**Comment by bhamodi** [comment]
Fixed in #102.
