### ISSUE TITLE
Internet Explorer 8 support?

### ISSUE THREAD

**Issue by firstdoit** [optimizely/nuclear-js#107]
I hate to be the guy to ask, but does NuclearJS support IE8? I don't see any reason why it *shouldn't*, but it doesn't hurt to ask. Apparently ImmutableJS [supports it fine](https://github.com/facebook/immutable-js/issues/45).

**Comment by jordangarcia** [comment]
We dont support IE8 out of the box due to the use of ES5 features.  NuclearJS _should_ be fine with an `es5-shim`

**Comment by firstdoit** [comment]
OK, perfect. Do you think we should add the shim and IE8 to the tests?

**Comment by jordangarcia** [comment]
This is something that is pretty low priority for us at Optimizely as we dont support IE8

However if you are interseted in doing this I'd be happy to accept a PR.

**Comment by bhamodi** [comment]
@firstdoit - are you interested in sending a diff for this?

**Comment by firstdoit** [comment]
Sorry, I don't have the time right now :/ but `es5-shim` is a must-have anyways! Cheers!

**Comment by karmakoder** [comment]
@jordangarcia does optimizely support IE8?

**Comment by jordangarcia** [comment]
We do not.  NuclearJS currently uses many features only found in es5 and
does not officially support IE8 and below.

You can try including an es5 polyfill, but we do not gaurantee support.
