### ISSUE TITLE
How does a store call a getter?

### ISSUE THREAD

**Issue by tilomitra** [optimizely/nuclear-js#108]
I realize this may be a very dumb question, but I cannot figure it out :cry: Consider this action:

**actions.js**
```js
exports.clickThread = function(threadID) {
  flux.dispatch(actionTypes.CLICK_THREAD, { threadID })
}
```

And this store:

**current-thread-id-store.js**
```js
module.exports = new Nuclear.Store({
  getInitialState() {
    // only keeps track of the current threadID
    return null
  },

  initialize() {
    // all action handlers are pure functions that take the current state and payload
    this.on(actionTypes.CLICK_THREAD, setCurrentThreadID)
  }
})

function setCurrentThreadID(state, { threadID }) {
  // return the new value of the store's state
  return threadID
```

and this getter:

**getters.js**
```js
exports.currentThreadID = [
  exports.currentThread,
  thread => thread ? thread.get('threadID') : null
]
```

How does the store method (`setCurrentThreadId`) know to trigger the getter (`currentThreadId`)? In my React component, I'm calling the action (`clickThread()`), but `render()` is never getting called, because the getter is not being triggered. What am I missing here? Is there some naming convention between the store method and the Getter method?

**Comment by Casen** [comment]
In your getters.js file you appear to be missing the exports.currentThread method.

In order for currentThreadID to return a value, currentThread must return a result rather than be undefined.

```javascript
exports.currentThread = [
  ['currentThreadID'],
  exports.threadsMap,
  (currentThreadID, threadsMap) => threadsMap.get(currentThreadID)
]
```
You should notice they reference each other, but rather than a circular reference via exports.currentThreadID, it's referenced via it's name. The first pass will be null, but once currentThreadID get's set, current thread is set as well.

**Comment by colindresj** [comment]
> How does the store method (setCurrentThreadId) know to trigger the getter (currentThreadId)?

@tilomitra It's important to understand that the store method doesn't directly trigger a getter's revaluation. Stores methods are simply responsible for returning state. That's all they do.

Under the hood, Reactor instances (usually referenced as `flux`) have a change observer. If state has changed after a store method is called, the change observer, will evaluate observing getters via an evaluator. Getter transform functions then receive the recursively evaluated data. In this way, those functions don't need to care at all about the store. The change observer and evaluator work together to make sure that a getter receives the correct data whenever state changes.

With all that said, if you have a registered store, you can create a getter directly from its keypath. So, if you wanted a getter to grab the currentThreadId, according to the currentThreadIdStore:

```js
exports.currentThreadID = ['currentThreadID']
```

If you wanted to actually grab the current thread by using the stored currentThreadId, then as @Casen wrote above:

```js
var currentThreadID = exports.currentThreadId = ['currentThreadID']

// Assuming a Map of threads
var threadsMap = exports.threadsMap = ['threads']

exports.currentThread = [
  currentThreadID, threadsMap, (id, threadsMap) => threads.get(id)
]
```

**Comment by bhamodi** [comment]
@tilomitra - both the above answers are correct. I'm closing this for now. Please feel free to reopen or make another issue if something else arises.
