### ISSUE TITLE
How would you suggest making store.getInitialState async? 

### ISSUE THREAD

**Issue by tonytamps** [optimizely/nuclear-js#118]
I need a store's `getInitialState` to load some data from IndexedDb (which is async).
I know that I can load a dummy initial state then load the IndexedDb stuff later but that causes some issues with an observer and some getters - It gets a bunch of dummy data, then the real data and I don't want to have to make a differentiation between the dummy/real data.

It would be much easier if `getInitialState` could be async and all data was the real data.

I got a working solution like this:

```javascript
// async-reactor.js - Mostly a Copy&Paste from nuclear-js/reactor.js

class AsyncReactor extends Reactor {
  registerStores(stores) {
    Bluebird.resolve(Object.keys(stores))
      .each(id => {
        var store = stores[id];
        if (this.__stores.get(id)) {
          /* eslint-disable no-console */
          console.warn('Store already defined for id = ' + id);
          /* eslint-enable no-console */
        }

        return Bluebird.resolve(store.getInitialState())
          .then(initialState => {
            if (this.debug && !isImmutableValue(initialState)) {
              throw new Error('Store getInitialState() must return an immutable value, did you forget to call toImmutable?');
            }

            this.__stores = this.__stores.set(id, store);
            this.__state = this.__state.set(id, initialState);
          });
      })
      .then(() => this.__changeObserver.notifyObservers(this.__state));
  }
}
```

And it's used like this:
```javascript
// app.jsx - app entry point
export default React.createClass({
  getInitialState() {
    return {
      appLoaded: false 
    };
  },

  componentWillMount() {
    // When the app has finished loading, set the state to true
    AsyncReactor.observe(() => this.setState({appLoaded: true}));
  },

  componentWillUpdate(nextProps, nextState) {
    // Once the state is true, go to login
    if (nextState.appLoaded) {
      this.transitionTo('/login');
    }
  },

  render() {
    // Shows a pretty loading screen while the app loads.
    return (<div>LOADING...</div>);
  }
```

Now `store.getInitialState` can return a promise or non-promise value.
Once the app is loaded, the stores all function like normal.
It adds a slight delay to startup but I can make that look fine.

There is some room for improvement, especially in the `observe` that watches the AsyncReactor, but I'll optimise it later.

It's stepping outside the box is making me slightly uncomfortable. Any ideas for a better way?
My preference would be to enhance the Nuclear-js code if possible. Happy to make PRs if you can see some room for improvement.

**Comment by colindresj** [comment]
Maybe I'm missing something, but why not use an action instead?

Inside of your `app.jsx`
```js
getDataBindings() {
  return { appReady: Getters.appReady };
},

componentWillMount() {
  Actions.loadAppData();
},

componentWillUpdate(nextProps, nextState) {
  if (nextState.appReady)) {
    this.transitionTo('/login');
  }
}
```

Inside of your `actions.js`
```js
loadAppData() {
  fetch().then(data => { // You can do async stuff inside of actions
    flux.dispatch('APP_READY', { data })
  }).catch(err => ...)
}
```

Inside of your app ready store
```js
getInitialState() {
  return false
},

initialize() {
  this.on('APP_READY', () => true)
}
```

The above should give you what you want without changing the way reactors work.

I would alternatively suggest, bootstrapping your app instead of loading data asynchronously, but to each his own on that front.

**Comment by tonytamps** [comment]
I might not have been clear enough. Almost all of my stores are loading data from IndexedDb. This data is watched by an observer on the reactor.

If my store has this: 
```javascript
getInitialState() {
  return false
},
```

Then my observe and getters will all need to do checks on `if (appReady === false)` to filter out all of the "bad" data being emitted before loading.

Using promises or callbacks, no data is emitted until the stores have loaded their persisted data from IndexedDb.

**Comment by jordangarcia** [comment]
+1 to the idea of having a specific store to track you application "ready" state and using that in your getters to only expose the data when its ready.

In general I think its simpler to load all of your data upfront and then when that is done run the UI (that's how we do it at Optimizely)

**Comment by jtremback** [comment]
@jordangarcia This is not easy in react-native. I have not been able to make it work.

I'm using actions, which is annoying and verbose. Not saying that's bad, but it is what it is.

**Comment by tonytamps** [comment]
I think this has been addressed enough to close it.

Thanks.
