### ISSUE TITLE
Unpredictable behavior when including many modules that share the same Reactor.

### ISSUE THREAD

**Issue by pbeets** [optimizely/nuclear-js#120]
I'm running into an issue where I have separate modules that are imported at different files of the application. On import, the modules each call `reactor.registerStores(stores)` on their own stores. However, this causes the getters to sometimes evaluate to `undefined` breaking the transform function.

I've traced this issue to the `__prevState` on __ChangeObserver sometimes being called with the wrong `newState` when `reactor.dispatch` is called on asynchronous requests.

Is this a bug? What is the best way to register different stores in different React components?

**Comment by jordangarcia** [comment]
hmm, so if i am understanding this correctly it looks like this:

```
registerStores(module1) -> async action -> registerStores(module2) -> dispatch as a result of async action
```

And the incorrect prevState is getting passed to the `ChangeObserver` in the dispatch after the async action, not accounting for the new AppState due to `registerStores`?

**Comment by pbeets** [comment]
Correct, so it would be

file1.js:

```
import module1; // registerStores
module1.asyncAction(); // dispatch
```

file2.js
```
import module2; // registerStores
module2.action(); // dispatch
module2.asyncAction(); // dispatch

{
  getDataBindings() {
    return {
      obj: module2.getters.obj // [['store2a'], ['store2b'], (a, b) => { a.find(b) }]
    }
  }
}
```


And behavior happens as expected up to `module2`'s first action. Then on it's async action dispatch, the state of reactor is correct, and it passes the correct `newState` to `ChangeObserver.notifyObservers`. But when inspecting `this.__prevState` it is of an older value, before module2's stores were registered causing `prevValue = this.__evaluator.evaluate(prevState, getter)` to throw an error in the transform since it is expecting at least some default values.

Moving the `import module2;` to file1.js solves this issue as file1 is closer to the beginning of the app lifecycle.

**Comment by jordangarcia** [comment]
I am trying to reproduce this and cannot.   Which version of NuclearJS are you using?

**Comment by pbeets** [comment]
I am using the latest commit of nuclear. The problem is very odd and it is repeatable in multiple browsers.  I'm not using anything special complex code either.

**Comment by jordangarcia** [comment]
Would you mind making a js bin with the conditions it throws an error.
Unfortunately I cannot reproduce

**Comment by pbeets** [comment]
I suspect the error was coming from loading routes asynchronously using the new react-router beta. We have since switched away from that and I am not experiencing that issue anymore.
