### ISSUE TITLE
Documentation in gh-pages are broken

### ISSUE THREAD

**Issue by adisuryadi** [optimizely/nuclear-js#121]
Looks like the base url changed to http://localhost:4000/ instead of originally https://optimizely.github.io/nuclear-js/

**Comment by bhamodi** [comment]
Hi @adisuryadi,
So it appears, all the optimizely.github.io pages were replaced with localhost:4000 is this commit: https://github.com/optimizely/nuclear-js/commit/2f7261c1b54cd10d86c708421d51e0a3ac748653
But the changes seem to have been reverted in this commit: https://github.com/optimizely/nuclear-js/commit/226ef3c239696a1d9d8a6084b84a7e4dea1a4731

Can you try on the latest version and let me know if this has been resolved?

**Comment by jordangarcia** [comment]
thanks @adisuryadi fixing now

**Comment by jordangarcia** [comment]
Fixed
