### ISSUE TITLE
Coveralls CI hangs.

### ISSUE THREAD

**Issue by bhamodi** [optimizely/nuclear-js#126]
@jordangarcia - on the last 3 PRs it seems that coveralls CI task is just hanging. I don't think we changed anything from our side, so not sure what's up there. Could this have to do with the new eslint CI configuration?

**Comment by bhamodi** [comment]
Issue was from Coveralls side of things. Closing.

**Comment by rsinnet** [comment]
@bhamodi Could I ask what the problem was? I'm seeing this issue on another repo and am trying to resolve it. Thanks!

**Comment by bhamodi** [comment]
Hey @rsinnet - it was determined that it was just a transient issue from Coveralls. We didn't have to change any configuration.
