### ISSUE TITLE
Debugging state changes not updating React class

### ISSUE THREAD

**Issue by auser** [optimizely/nuclear-js#127]
Currently I'm working with a React component that renders with the state initially, but when the state is updated through a getter, it does not trigger a re-render.

The component is:

```javascript
  var DashboardPane = React.createClass({
    mixins: [reactor.ReactMixin],
    getDataBindings() {
      return {
        data: DashboardModule.getters.data,
      }
    },

    getInitialState() {
      return {
        startAt: moment(new Date()).subtract(3, 'months').toDate(),
        endAt: moment(new Date()).toDate(),
      }
    },

    componentDidMount() {
      this._fetchData();
    },

    _fetchData() {
      let {startAt,endAt} = this.state;
      DashboardModule.actions.find('data', start_at: startAt, end_at: endAt})
    },

    render() {
      let data = toImmutable({
            data: this.state.data,
          });

      return (
        <div className="dashboard-main">
          <Dashboard data={data} />
        </div>
      )
    }
  });
```

Where the getter is simple enough:

```javascript
const dataGetter = ['data'];
```

And the store is pretty standard as well...

I may be implementing something incorrectly, but other components in my app are working as expected. With debug mode turned on, I do see that the state is changing, but the react component isn't triggered. None of the usual `shouldComponentUpdate` or `componentDidUpdate` are fired.

Any ideas?

**Comment by jordangarcia** [comment]
What does your store look like?

Is t already coercing the data toImmutable?

Also what happens if you get rid of getInitialState and hard code the date
values in?

**Comment by auser** [comment]
The store

```javascript
var {toImmutable, Store} = require('nuclear-js')
var dashboardActionTypes = require('../dashboardActionTypes');
var apiActionTypes = require('../../rest-api/actionTypes');
var _ = require('lodash');

module.exports = Store({
  getInitialState() {
    return toImmutable([]);
  },

  initialize() {
    this.on(apiActionTypes.API_FETCH_SUCCESS, loadEntityData);
    this.on(apiActionTypes.API_DELETE_SUCCESS, onDeleteSuccess);
  },
});

function loadEntityData(state, payload) {
	var entity   = payload.entity;
  var result  = payload.result;
  var name    = payload.name;
  var data = result;

  if (data && data[name])
    data = data[name]; // Nested results

  if (!_.isArray(data)) {
    data = [data]
  }

  return state.withMutations(state => {
    data.forEach(entry => {
      var imObj = entry.toImmutable ? entry.toImmutable() : toImmutable(entry);
    	state.push(imObj);
    });
  });
}

/**
 * payload.id
 * payload.entity
 * @param {Immutable.Map} state
 * @param {object} payload
 */
function onDeleteSuccess(state, payload) {
  var entity = payload.entity
  var id = payload.id

  return state.removeIn([entity, id])
}
```

I'll check your question in a minute

**Comment by auser** [comment]
No such luck :/

**Comment by auser** [comment]
A clue. I'm receiving the error: `Non-extensible objects are not allowed as keys.');`

Digging through immutable source now... Perhaps this might help us discover the bug? The workflow is pretty standard, the stores, actions, getters, etc. are straightforward and closely related to the guide.

**Comment by auser** [comment]
One more clue:

With the getter:

```
module.exports = {
  data: ['data']
}
```

This throws the same error as above:

```javascript
reactor.observe([
    ['data'],
    function(items) {
      console.log('items changed', items);
    }
  ]);
```

**Comment by auser** [comment]
Turns out that the problem was _not_ nuclear. After lots of debugging, it's that we weren't including `babel/browser-polyfill`. Without this polypill, `Object.isExtensible` returned `false` inside the app, vs. outside where it returned true. 

Super confusing.
