### ISSUE TITLE
Prescribed Testing Strategies

### ISSUE THREAD

**Issue by gf3** [optimizely/nuclear-js#128]
It's mentioned throughout the docs and the website that there are "prescribed testing strategies" and "there is never a question of 'How do I test this?'". However I couldn't actually find any information about this—I was wondering if there's any documentation or guidance anywhere about idiomatic testing with Nuclear JS? Thank you.

**Comment by seethroughtrees** [comment]
+1, Wow, I just went to issues to ask this exact same question.  Hoping those strategies get released soon!  Thanks.

**Comment by jordangarcia** [comment]
This will be the next section in the documentation.  Sorry for the wait!

**Comment by seethroughtrees** [comment]
No problem at all.  Was just looking everywhere, glad its coming soon.  Thanks for all of it...

**Comment by jwicksnin** [comment]
+1 Would like to see these as well!

**Comment by adisuryadi** [comment]
+1

**Comment by freynl** [comment]
+1

**Comment by jordangarcia** [comment]
Hey Guys,

Sorry i've been so absent on this task.  Will have something up by this weekend :D

**Comment by kamui** [comment]
I'm looking forward to this too.

**Comment by jordangarcia** [comment]
Here is the first set of documentation. https://optimizely.github.io/nuclear-js/docs/08-testing.html

Would love more suggestions on things to cover.  Optimizely has a very extensive testing strategy built foundationally on NuclearJS and our UI framework.  

This documentation cover our core unit tests for our NuclearJS modules (which constitute a large portion of our codebase).

**Comment by adisuryadi** [comment]
awesome! thanks @jordangarcia

**Comment by gf3** [comment]
:+1:

**Comment by seethroughtrees** [comment]
Definitely looks like a great start.  I'll implement these over the weekend and see how it goes...

**Comment by bhamodi** [comment]
Closing this issue now as testing documentation is currently live at: https://optimizely.github.io/nuclear-js/docs/08-testing.html
