### ISSUE TITLE
Dispatching from an observer will cause observer to be called twice

### ISSUE THREAD

**Issue by balloob** [optimizely/nuclear-js#130]
If I observe a value in storeA, and in that observer call an action that will change the state in store B, the observer for the value in store A will be called twice with the same new value. If the action that is triggered does not change the state in storeB, the observer is not called twice.

In the following code, `new value for store A true` is printed twice. Uncommenting `return state` in the action handler of store B and `new value for store A true` is only printed once.

```javascript
var Nuclear = require('nuclear-js');

var storeA = Nuclear.Store({
  initialize: function() {
    this.on('ACTION_A', function(state, payload) {
      return payload.hello;
    });
  }
});

var storeB = Nuclear.Store({
  initialize: function() {
    this.on('ACTION_B', function(state, payload) {
      // Uncomment to have bug not happen
      // return state
      return Nuclear.toImmutable(payload.value);
    });
  }
});

var reactor = Nuclear.Reactor({debug: true});

reactor.registerStores({
  storeA: storeA,
  storeB: storeB
});

var storeAGetter = ['storeA'];

reactor.observe(storeAGetter, function(value) {
  console.log('new value for store A', value);
  reactor.dispatch('ACTION_B', {value: 'set'});
});

reactor.dispatch('ACTION_A', {hello: true});
```

**Comment by balloob** [comment]
In the dispatcher made by Facebook, they raise an error if you try to dispatch while dispatching ([source](https://github.com/facebook/flux/blob/master/src/Dispatcher.js#L182-L185)).

**Comment by balloob** [comment]
The problem arises because while [`notifyObservers`](https://github.com/optimizely/nuclear-js/blob/master/src/change-observer.js#L26-L54) is calling the observers, it is being called again by the new dispatch.

I can think of three solutions:

  1. Raise an error while trying to dispatch while dispatching
  2. Queue the calls to `dispatch` and dispatch them after `notifyObservers` is done
  3. Change `notifyObservers` to allow it being called a second time while calling handlers. (this will get very messy with as it allows for handlers being notified of state T+2 before being notified of state T+1).

**Comment by jordangarcia** [comment]
I like the solution of throwing an error if a dispatch happens within an
observe.

Would you like to PR this functionality?

**Comment by balloob** [comment]
Sure. Will work on it in a bit.
