### ISSUE TITLE
Rehydration via "loadState" is not working properly for a Store holding data in a Map

### ISSUE THREAD

**Issue by freynl** [optimizely/nuclear-js#142]
I modified the shopping-cart example for a prototype I'm working on.  I augmented the functionality to play with some concepts we are looking at (this is my first attempt at using React and Nuclear).  I also modified it to be isomorphic, using what information I could find on the subject and https://github.com/jordangarcia/nuclear-js-react-addons features.  

I am successfully dehydrating and rehydrating the state via the functions below.  The state_text is a string of JSON data taken from the DOM.

<pre>  
dehydrate: function(reactor) {
    return JSON.stringify(reactor.serialize())
  },

  rehydrate: function(reactor, state_text) {
    reactor.loadState(JSON.parse(state_text))
  }
</pre>
The state seems to have been hydrated properly, however, the loaded state seems to not be re-mapping the "products" properly.  The ProductStore.decrementInventory (taken directly from the shopping_cart example) keeps failing on the _product.get('inventory') line below because _product is undefined:
<pre>
function decrementInventory(state, { product }) {
  console.log(product)
  console.log(state.get(product.id))
  console.log(state.get([product.id]))
  console.log(state.getIn([product.id]))
  console.log(state.getIn([product.id, 'inventory']))

  return state.update(product.id, _product => {
    const currentInventory = _product.get('inventory')
    const newInventory = (currentInventory > 0) ? currentInventory - 1 : 0;
    return _product.set('inventory', newInventory)
  })
}
</pre>
I did some investigation and no matter how I attempt to get a product from the state in the log statements, it is always undefined.  If I modify my client to call actions.fetchProducts(reactor) on document load rather than use the dehydrated state, it works fine.  Also, another simpler Store I created for maintaining a User state object is able to be dehydrated and rehydrated just fine.  This appears to be an issue with the case of using a map.  

Thank you!

**Comment by freynl** [comment]
Letting you know that I was able to make my store hydrate and dehydrate by implementing the serialize and deserialize methods on the ProductStore as a workaround.    

serialize(state) {
    if (!state) {
      return state
    }

    return state.toList().toJS()
  },

  deserialize(state) {
    return toImmutable(state)
    .toMap()
    .mapKeys((k, v) => v.get('id'))
  }

**Comment by jordangarcia** [comment]
Yeah unfortunately due to JS objects coercing keys to strings its not possible to have default serializations of an Immutable.Map.

The approach you took is correct.
