### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by auser** [optimizely/nuclear-js#154]
I'm using nuclear with react native, but running into some curious issues. Curious if anyone else has successfully used nuclear with react native.

**Comment by jordangarcia** [comment]
Hey Ari!

I've successfully used NuclearJS in a couple of React Native apps.  What sort of issues are you running in to?

**Comment by auser** [comment]
Wow... that was quick. I should be more specific. 

The second dispatch through `reactor.dispatch` doesn't fire. (Had a different issue before it seems -- but looks like that one is resolved, not related to nuclear).

Any ideas as to why my dispatch wouldn't work?

**Comment by jordangarcia** [comment]
Hm, without more information I am not sure why a `reactor.dispatch` wouldn't be firing.

Is it part of an event handler / callback.  More specifically is it part of a callback within the NuclearJS system?

**Comment by jordangarcia** [comment]
There are a few reason's why a dispatch wouldn't go throw but most of them should raise errors.  See: https://github.com/optimizely/nuclear-js/blob/master/src/reactor.js#L110-L142

**Comment by auser** [comment]
Good idea to check out the source (of course!)

I'm firing the dispatch as part of an action function (with dummy data -- aka no promise-based callback):

```javascript
var actions = {
  getData: (key) => {
    var obj = {
      key: key,
      data: data[key]
    }
    console.log(obj);
    reactor.dispatch(actionTypes.DATA_FETCHED, obj);
    console.log('getdata', toImmutable(obj));
  }
};
```

**Comment by auser** [comment]
Yep, okay... so react-native is swallowing the error. It's because it's part of a callback and the previous dispatch hasn't resolved yet.

Thanks for the quick response. Closing now

**Comment by jordangarcia** [comment]
Cool, glad you figured out.

One thing I had to cosntantly do when building/debugging react-native apps, was to set a breakpoint early in the app js code then turn on "Pause on caught exceptions"

**Comment by auser** [comment]
Hm... seems like `this.__isDispatching` never is set to false.. When is a dispatch complete?

**Comment by jordangarcia** [comment]
Under a normal dispatch happens: https://github.com/optimizely/nuclear-js/blob/master/src/reactor.js#L140

Could it be possible that something in the app is throwing an error and isDispatching isn't getting set back to false?

Although we should be preventing all codepaths where an error can be thrown within a dispatch:
https://github.com/optimizely/nuclear-js/blob/master/src/reactor.js#L133-L138

**Comment by auser** [comment]
Yeah, that's what I'm looking at... I'm not seeing an error and it seems like the second dispatch is being called before the `this.__notify()` completes. Feels like a race condition, but not sure how that would actually even happen.

**Comment by jordangarcia** [comment]
Yeah that seems absolutely strange that a race condition could even exist.
I've heard reports of similar issues, but haven't been able to reproduce.

Can you paste in the two dispatch invocations that are clashing?

Just to be sure, you aren't dispatching in a store handler or observe
function?

**Comment by auser** [comment]
I just changed the way I did it :/. Using a callback instead of nuclear in this one particular spot. Bummer.
