### ISSUE TITLE
isomorphic-flux-chat example crashes

### ISSUE THREAD

**Issue by aldanor** [optimizely/nuclear-js#157]
Seems like this line has to be fixed in the `isomorphic-flux-chat` example:

```js
var _state = JSON.stringify(reactor.__state.toJS());
```

as it causes it to crash:

```console
> nodemon server.bundle.js --watch server.bundle.js --watch client.bundle.js --watch index.html

19 Aug 21:55:38 - [nodemon] v1.4.1
19 Aug 21:55:38 - [nodemon] to restart at any time, enter `rs`
19 Aug 21:55:38 - [nodemon] watching: server.bundle.js client.bundle.js index.html
19 Aug 21:55:38 - [nodemon] starting `node server.bundle.js`
Listening on port 1337
Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset
/Users/ivansmirnov/dev/forks/nuclear-js/examples/isomorphic-flux-chat/server.bundle.js:110
        var _state = JSON.stringify(reactor.__state.toJS());
                                                   ^
TypeError: Cannot read property 'toJS' of undefined
    at Server.<anonymous> (/Users/ivansmirnov/dev/forks/nuclear-js/examples/isomorphic-flux-chat/server.bundle.js:110:49)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```

**Comment by bhamodi** [comment]
Thanks for filing this @aldanor.

@Sinewyk - could you take a look at this? This is the example you added I believe. Thanks!

**Comment by Sinewyk** [comment]
No errors after in this order
```bash
npm i
npm run watch #in one terminal
npm start -- --port=9003 #in another terminal
```

And then opening my browser and going to http://localhost:9003, everything works fine.

node v2.3.4

Did you do anything specific @aldanor ?

**Comment by aldanor** [comment]
@Sinewyk I did just exactly that to double check and yes, it does still crash. Are you using the latest version from git?

**Comment by Sinewyk** [comment]
yep, rebased master just before trying, I'm going to recheck by `rm -R` my node_modules folder to confirm i'm starting from scratch.

**Comment by Sinewyk** [comment]
Nice, got the bug by reinstalling modules from scratch, let me see =)

**Comment by Sinewyk** [comment]
Meh, easy fix, that's what I get by reading a "private" variable. I'll fix the example by actually removing the todo "refactor when nuclear 1.1 lands" ...

https://github.com/optimizely/nuclear-js/commit/de35e194296c0d61d682c0e895aa4e2ddd89d7ba#diff-889e806243cf10b2e10689e9632f17a2L38

**Comment by aldanor** [comment]
Yep, that looks like it :)
