### ISSUE TITLE
App organization

### ISSUE THREAD

**Issue by colindresj** [optimizely/nuclear-js#16]
There's mention of eventually providing documentation around structuring large nuclear apps using modules, but since that's not provided yet, I was hoping to get some insight on the recommended convention.

I've taken a look at [Tetris](https://github.com/jordangarcia/tetris), and see where things are going, but it would be awesome to know more about when/why to use modules and any other org details.

**Comment by jordangarcia** [comment]
Tetris starts to show the organizational structure of large nuclear apps.  Optimizelys main frontend app is structure with the same module pattern.  I will release a more thorough documentation and example app with the module pattern when Nuclear 0.6.0 is relased (the next branch) which is what we are currently using.

**Comment by colindresj** [comment]
Awesome, looking forward to it.
