### ISSUE TITLE
Issue with `reactor.loadState` not updating all bindings

### ISSUE THREAD

**Issue by tonytamps** [optimizely/nuclear-js#164]
I've got an issue where it seems like if I `reactor.loadState` inside a component, that component will no-longer receive updates for (some of?) it's bindings but child components still do.

Here is a JSFiddle replicating the issue.
https://jsfiddle.net/o8mths43/2/

**Notes:**

 - `setTimeout` at the top simulating an action to update the store. 
   - It works fine **if** `loadState` isn't called before hand.
   - you can see the parent/child binding change in the rendered page.
 - `prop1` binding is only updated in the child component after the loadState 
 - `prop2` is based on `prop1` and is unable to get updated even when changing the value of `prop1` after the `loadState`

I hope this is just me using loadState incorrectly. Have you come across this? 

It's 6am and I'm not sure I'm making a lot of sense. Take a look and see if you can reason out what I'm getting at. Happy to answer more questions and explain if needed.

**Comment by tonytamps** [comment]
I've not made any progress on this and I suspect there have been a couple other interactions that have been similar.

Any suggestions or info @jordangarcia ?

**Comment by c-spencer** [comment]
Given you're mounting/unmounting things, you could be running into #151 which is fixed on master.

**Comment by tonytamps** [comment]
@c-spencer I did try this on master at the time too. I thought the same thing. 

I assume calling `loadState` is doing a similar thing to `reset` and causing observers attached at the time to be dropped.

**Comment by c-spencer** [comment]
Quick look, if you do the loadState inside a componentDidMount instead of componentWillMount then it works, so it's likely some issue in there/reactMixin rather than loadState itself.

**Comment by tonytamps** [comment]
I tried it outside of the react hooks totally, as soon as the file was required and it didn't work. I'll try in componentDidMount when I get back to a computer.

**Comment by tonytamps** [comment]
Can still replicate in my code base even when using `componentDidMount`. May not be the same issue but has the same symptoms.

**Comment by bhamodi** [comment]
Are you still having issues with this @tonytamps?

**Comment by tonytamps** [comment]
Hey @bhamodi 
Yes, we've got a work around but I was really hoping that we could get some more info on this to avoid hacky solutions.

**Comment by jordangarcia** [comment]
hm this seems like it should work.

1.2 will be released this week and it rewrites the loadState function

**Comment by tonytamps** [comment]
We'll test it and get back to you @jordangarcia

**Comment by jordangarcia** [comment]
@tonytamps I believe `1.2` should fix this.  If it doesn't can you let me know and I'll look into the issue further.

**Comment by tonytamps** [comment]
@jordangarcia It doesn't immediately fix the jsfiddle example I gave. It does work if I change the `compoentWillMount` to `componentDidMount`.

I'll check in our production code example if it works there.

**Comment by tonytamps** [comment]
@jordangarcia I've had a long think and test with this `loadState` issue.

Changing `componentWillMount` to `componentDidMount` is actually a really bad idea. The problem is just hidden when that happens.

The root issue (as far as I can see) is that when performing the jsfiddle _exactly_ how it is now shows a few things:

 - After `loadState` the child component has the correct values and the parent does not. It seems `loadState` inside the parent component does not trigger an update to the parent's bindings. This is fine, I'm happy to assume that is a timing issue to do with the binding not being connected. Lets ignore this.
 - The `ACTION` that occurs two seconds after the `loadState` causes an update to `prop1` in both parent and child component. This is great! It means we're back on track, the system just corrected itself.
 - the `prop2` getter (which is calculated from `prop1`) is never run and not updated in the parent component. Even though the state of the store changes, the getter is not triggered for the component that called `loadState`. Now both components have a different value for `prop2` even though they both have the same value for `prop1`.

**Comment by tonytamps** [comment]
@lyonlai has worked this out.

It is just a timing issue with the store's cached value and moving it into `componentDidMount` isn't masking a bit, it's a valid fix. Setting values that would cause another update get the cached value back in line with the rest of the system from then on.

It would be nice to throw a warning if `loadState` is run inside `componentWillMount` to avoid anyone else having to deal with weird cache issues.

I guess I can close this now?
