### ISSUE TITLE
Minor Usage Docs Clarification

### ISSUE THREAD

**Issue by hnordt** [optimizely/nuclear-js#169]
At:

https://github.com/optimizely/nuclear-js/blob/a920d0136be463be962fec5d9ab4eb76188c5828/docs/src/components/usage-example.js#L144

Changing:

`(storeState, action) => (newStoreState)`

To:

`(storeState, actionPayload) => (newStoreState)`

Will be easier to understand for newcomers like me.

When I first looked at it I thought that I have the full action immutable object, even with type, then scrolling down I've see that's actually just the action payload.

It's just a suggestion :)

--

I've used many Flux Implementations. The "king" Facebook Flux, Baobab, Alt and Redux. NuclearJS is just awesome. It's easy to reason about, it's fun to use, the docs are simple and easy to consume. Thank you for this brillant library!

**Comment by tonytamps** [comment]
Just make a PR for it?
Also, the 3rd arg in that function is `actionType` - It's little known.

**Comment by bhamodi** [comment]
Feel free to send us a PR @hnordt! :)
