### ISSUE TITLE
Back (state history) or undo (change tracking)?

### ISSUE THREAD

**Issue by ariutta** [optimizely/nuclear-js#17]
Hello,

I was at your lightening talk at this [meetup](http://www.meetup.com/AngularJS-SF/events/218598993/), and I seem to remember this library enabled version tracking (aka change history).

I'd like to add "[Undo](http://c2.com/cgi/wiki?BackIsNotUndo)" functionality to an in-brower app, and from the docs, I see this:

```
Stores are self managing state, providing a single canonical place to define the behavior a domain of your application over time.
```

But is that talking about tracking high-level state history (like the browser back button needs to return to the previous "page") or granular-level change history (like an undo button needs).

Thanks!

**Comment by jordangarcia** [comment]
Hey Ariutta,

NuclearJS doesnt support undo / redo out of the box since every applications implementation may be a bit different given the UI framework used.

A simple implementation is to use the `reactor.loadState` method https://github.com/optimizely/nuclear-js/blob/master/src/reactor.js#L214 and `reactor.observe`.

```js
var reactor = new Nuclear.Reactor();
var historyReactor = new Nuclear.Reactor();

reactor.observe(function(state) {
  historyReactor.dispatch('SAVE_STATE', state)
})
// this will cause any change in the `reactor` to be dispatched as an action in the historyReactor
// then use a mechanic like the following
function gotoState(index) {
  var state = historyReactor.get(['state', index]);
  reactor.loadState(state);
}
```

This is off the cuff code but the concept is something I had implemented before.

**Comment by ariutta** [comment]
Thanks for the example. If I'm understanding it correctly, "Undo" vs. "Back" can be thought of as useful shorthand ways to refer to different levels of abstraction for state.  And since NuclearJS models state at whichever level we want, we can build on top of it to support both Undo and Back functionality.

If I get the time, I'd like to build an example of this along with a NuclearMithrilMixin for [Mithril](https://github.com/lhorie/mithril.js).
