### ISSUE TITLE
[QUESTION] Is it a bad practice?

### ISSUE THREAD

**Issue by hnordt** [optimizely/nuclear-js#170]
Hello.

I want to know if dispatching two different types of actions inside a module is a bad practice.

For example, I have two modules: profile and notification.

Profile dispatches notification actions:

```js
updateProfile(data) {
  reactor.dispatch(actionTypes.USER_PROFILE_UPDATE_START);

  updateProfile(data).then(data => {
    reactor.dispatch(actionTypes.USER_PROFILE_UPDATE_SUCCESS, data);

    reactor.dispatch(notificationActionTypes.SEND_SUCCESS_NOTIFICATION, {
      title: 'Profile Updated',
      message: 'Your profile was updated!'
    });
  }).catch(({ message }) => {
    reactor.dispatch(actionTypes.USER_PROFILE_UPDATE_FAILED, { message });

    reactor.dispatch(notificationActionTypes.SEND_ERROR_NOTIFICATION, {
      title: 'Profile Update Error',
      message
    });
  });
}
```

The problem I see is that now this two modules are coupled, and it's actually a bad practice. I want the modules to be loose coupled.

There is a better approach?

**Comment by mindjuice** [comment]
It looks to me like Profile uses and is aware of Notification, but Notification doesn't know anything about Profile, so the coupling at least is one way.

Profile only depends on the public interface of Notification, so the coupling there is fairly minimal IMO.

You could decouple them completely by injecting a ``notify`` function via closures when importing the module.  Something like this (not tested, but should work!):

    // In your module's index.js
    // Export a function that takes notify as an arg.  When called, the function will 
    // inject notify into Actions and return the Actions/Getters object.
    export default function(notify) {
      var actions = require('./actions');
      return {
        // Inject notify into the actions
        Actions: actions(notify),
        Getters: require('./getters')
      };
    };


    // In your actions file
    // Export a function that, when called, returns the actions as before,
    // but now 'notify' is available from the outer scope via closure.
    var actions = function(notify) {
      return {
        updateProfile: function(data) {
          // As before in your code, but with the notifications done this way
          notify('Profile updated', 'Your profile was updated!');
        }
      };
    };

    export default actions;


    // Usage
    var Notifications = require('./notifications');
    var notify = function(success, title, message) {
      if (sucess) {
        Notifications.Actions.sendSuccessNotification(title, message);
      } else {
        Notifications.Actions.sendErrorNotification(title, message);
      }
    };

    var Profile = require('./profile');
    Profile = Profile(notify);

**Comment by jordangarcia** [comment]
I think it's fine to have one module know about the another module (or even depend on it).

The part that I would say is a little too coupled is that you code is calling dispatches using actionTypes from two different modules.

However, given that one module is a notification module this seems a little too coupled IMO since a Notification module is more a UI level module and shouldn't be linked directly to business logic.  ie its perfectly plausible to want to update a user profile without showing a notification.

If I were doing this I would compose the two modules at the component level.

```js
Profile.action.updateProfile(data).then(function(resp) {
  Notification.actions.sendSuccessNotification({
       title: 'Profile Updated',
      message: 'Your profile was updated!'
  })
}, function(reason) {
  Notification.actions.sendErrorNotification({
       title: 'Profile Update Error',
      message: 'Your profile was updated!'
  })
});
```
