### ISSUE TITLE
Additional testing guidance

### ISSUE THREAD

**Issue by popc0rn** [optimizely/nuclear-js#174]
Hi guys!
I have a hard time figuring out the best approach to unit test our modules(actions, stores & getters).
I have seen the issue [#128](https://github.com/optimizely/nuclear-js/issues/128) and [docs about testing](https://optimizely.github.io/nuclear-js/docs/08-testing.html) that are pretty simple and straight forward in that example and mocked data is reasonable.

My stores have collections and data that are related to each other and sometimes I need to combine that resources to get wanted data for containers/components. Getters fetch that data exposed from multiple stores and depend on it.Problem occurs when I'm to test such getter/action. I need to mock a bunch of data and repeat that for every similar test. 
What is your approach to testing such getters and populating data stores before asserting correct return values from getters?
Because in your test example you noted "...we did not stub or mock any part of the NuclearJS system". As I understand, you are thinking about methods like **reactor.evaluate** or **reactor.dispatch** etc. For setting up state we are left with **reactor.loadState** and created actions.
What do you use to populate multiple stores for just one action or getter test?
Calling multiple actions to prepare terrain before testing another action doesn't seem like a solution.

I also have actions that evaluate state before dispatching. Is that an anti-pattern?

Maybe I need a completely different approach, but it's all a bit vague for me at the moment. Any recommendations, guidelines or suggestions would be welcome and helpful.
Thank you

**Comment by jordangarcia** [comment]
It's perfectly reasonable to have actions evaluate reactor state before dispatching.  A good way to think about NuclearJS is a large map of state that you can read and write to anytime (just writes have to go through `dispatch`).

We usually invoke whatever setup actions need to happen in tests if we are testing some action performing the proper state change, it's not ideal but sometimes this complexity is necessary.  Another way to simply testing is to make the store handler or getter a pure function that can be tested in isolation, which is much easier to test all use cases.  And then have a single test that ensures that the proper state of several actions takes place.

Hope this helps!

**Comment by popc0rn** [comment]
@jordangarcia just to make sure I understand. For example if the action we are testing depends on state set up by some other actions. We can call those actions to prepare the state and then call the targeted action and check for proper state change?
I have module that handles form editing and it consists among other things of few actions, and some depend on the other ones.
I.e. there are actions for registering form fields to store(init values), updating specific form fields and reseting all of them to init values.
If I'm to test reset action I would first need to register form, update some fields and in the end try to reset it to initial values. So, in this scenario you would just go ahead and call the required actions inside test case?

Thanks a bunch for your response I appreciate it

**Comment by jordangarcia** [comment]
Yeah I tend to be okay with calling actions in tests to setup the proper state, as this is actually the use case you'd more likely encounter in production.

There is a misconception that unit testing is inherently better, but I am very uncomfortable with having to mock all dependencies in a language without interfaces (javascript).  In a statically typed language like java you can implement mocks that conform to the same interface and know that you mocks are realistic in javascript mocking isn't so clean and can lead to tests passing when the actual code doesn't even do what you think it does.

**Comment by popc0rn** [comment]
Thank you very much @jordangarcia!
As you've answered and clarified the questions I'll close the issue.
