### ISSUE TITLE
Drop hard dependency on lodash

### ISSUE THREAD

**Issue by colindresj** [optimizely/nuclear-js#18]
Including lodash as a dependency has two undesirable side effects: 

1. Greatly increases the dist size of nuclear
2. Forces you to use lodash as your application utility library

My preferred solution would be to simply make lodash an optional dependency. I understand that the authors may want to keep using lodash functions, so as an alternative, only include the lodash functions currently being used by nuclear:

```js
var each = require('lodash.foreach'); // instead of require('lodash').each;
```

Thoughts @dtothefp ?

**Comment by dtothefp** [comment]
@colindresj is this a thing or not?

**Comment by colindresj** [comment]
@dtothefp I'd like it to be. Would be willing to submit a PR, but wanted to post an issue beforehand to get feedback, since it is a potentially impacting change.

**Comment by dshimkoski** [comment]
It would be great to get rid of such a large dependency.

Modularized lodash is a thing: https://www.npmjs.com/browse/keyword/lodash-modularized

**Comment by colindresj** [comment]
Agree @dshimkoski. Again, my preference would be to just make lodash an optional dependency, but if that doesn't seem realistic, then the individual lodash modules would help cut things down quit a bit.

My main thought with all this is that because lodash is such a heavy dependency, when using nuclear, you're almost forced into lodash for utilities, instead of other options that exist and maybe suit a particular person's project (or preference) better.

If a lot of lodash was being used throughout, this would be a non-issue, however since only a handful of functions are being used, it's kind of a shame to have to drag all of lodash along.

What's your opinion @jordangarcia?

**Comment by jordangarcia** [comment]
Hey Colin

I still the intention of removing lodash as a hard dependency of NuclearJS.   The way the codebase is structured the `utils` files is a facade over lodash and the methods being used can eventually be replaced with plain javascript reimplementations.

If anyone is interested in doing this I will gladly accept PRs

**Comment by colindresj** [comment]
Working on a PR, should be up soon
