### ISSUE TITLE
Inheriting from Reactor doesn't seems to work in v1.2.1

### ISSUE THREAD

**Issue by raulmatei** [optimizely/nuclear-js#191]
Hi,

It seems that inheriting from Reactor doesn't work as it worked before 1.2.x, is this something deliberate?

Ex:
  v1.2.1: http://goo.gl/cf2T99
  v1.1.2: http://goo.gl/zSMPAQ

Thanks,
Raul.

**Comment by jordangarcia** [comment]
Hey Raul,

I'm having trouble recreating this.

I see it happening in the codepen, but when i try to replicate it locally it works fine.

Here is my file:

```js
import Nuclear from './nuclear'

class Context extends Nuclear.Reactor {
  constructor(options) {
    super(options);
    this.modules = {};
  }

  logState() {
    return this.reactorState;
  }
}

const context = new Context({ debug: true });
console.log(context, context.logState());

const reactor = new Nuclear.Reactor({ debug: true });
console.log(reactor, reactor.reactorState);
```

**Comment by raulmatei** [comment]
Thanks Jordan,

It looks like this is Babel related, I have `es6.classes` in loose mode. Here is my `.babelrc` file:

```javascript
{
  "stage": 0,
  "loose": ["es6.modules", "es6.classes"],
  "optional": ["runtime"]
}
```
Removing `"es6.classes"` solves the issue. CodePen is probably using something similar and that's why it's reproducible in their environment.

Thanks,
Raul.

**Comment by jordangarcia** [comment]
@raulmatei is this still an issue then?

**Comment by raulmatei** [comment]
Not for me, I can remove the `es6.classes` from loose array, but it will brake if some one will try to use with a constructor function:

```js
function Context(options) {
  Nuclear.Reactor.call(this, arguments);
  this.modules = {};
}

Context.prototype = Nuclear.Reactor.prototype;
Context.prototype.constructor = Context;

Context.prototype.logState = function () {
  return this.state;
};

const context = new Context({ debug: true });
console.log(context, context.logState());

const reactor = new Nuclear.Reactor({ debug: true });
console.log(reactor, reactor.state);
```

Thanks,
Raul.

**Comment by jordangarcia** [comment]
Ah yeah that's true because the Reactor can be called without the new operator.

Thanks for figuring this out on your end Raul.

Closing.
