### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by talkhot** [optimizely/nuclear-js#192]
A lot of the libraries I use like react-intl/router are switching to React 0.14 and dropping support for 0.13.x I wonder if there is a plan or schedule to make Nuclear React 0.14 compatible?

**Comment by lyonlai** [comment]
@talkhot I don't think this library has problem supporting react 0.14 as we are on it and haven't find any difficulty with the upgrade.

**Comment by raulmatei** [comment]
NuclearJS is not dependent on React, you should be able to use it with any other UI (View) library as long as you can find a way to plug it in.

**Comment by jordangarcia** [comment]
NuclearJS works perfectly fine with React 0.14 :)
