### ISSUE TITLE
Question: How to best share Nuclear JS modules between projects?

### ISSUE THREAD

**Issue by iansinnott** [optimizely/nuclear-js#196]
I'm really enjoying the usage of modules as seen in the rest API example. I'm now using Nuclear JS in multiple projects and I have some functionality that is duplicated between projects.

For example, I have two projects that both have a Notifications module to manage the state of what notifications the UI should show the user. The module is exactly the same between projects. However, since each module needs access to the `Reactor` instance I haven't yet factored this functionality out into an NPM module.

Any thoughts on how best to handle something like this?

It would be nice to be able to do something like:

```js
// flux.js
import Notifications from 'nuclear-js-notifications';
import { Reactor } from 'nuclear-js';
const flux = new Reactor({ debug: true });
flux.registerStores(Notifications.stores);
export default flux;

// actions.js
import Notifications from 'nuclear-js-notifications';
api.post('/thing', { title: 'some thing' })
.then(res => {
  Notifications.actions.notify({ type: 'success', text: 'Success!' });
})
.catch(res => {
  Notifications.actions.notify({ type: 'error', text: 'Oh no!' });
});

// component.js
import Notifications from 'nuclear-js-notifications';
export const App = React.createClass({
  getDataBindings() {
    notifications: Notifications.getters.notifications,
  },
  render() {
    return (
      <ul>
        {this.state.notifications.map(notification => (
          <li className={notification.get('type')}>
            {notification.get('text')}
          </li>
        ))}
      </ul>
    );
  },
});

**Comment by raulmatei** [comment]
Hi,

I think the best way to do it is to export a `register` method on the module, that method will get the a `reactor` as an argument and it will register its stores. You should also export the actions/getters, so that you can use them in your components or in other modules.

Notifications:
```js
import notificationsStore from './stores/notifications';
import { * as actions } from './actions';
import { * as getters } from './getters';

export function register(reactor) {
  reactor.registerStores({ notificationsStore });
}

export actions;
export getters;
```

**Comment by balloob** [comment]
I did the same as what @raulmatei is suggesting but took it 1 step further.

All my modules export `register`, `actions` and `getters` ([example](https://github.com/balloob/home-assistant-js/blob/master/src/modules/auth/index.js)).

All my actions take in a reactor as their first param ([example](https://github.com/balloob/home-assistant-js/blob/master/src/modules/auth/actions.js#L47))

I have an [`exposeModule(target, reactor, modules)`](https://github.com/balloob/home-assistant-js/blob/master/src/util/expose-modules.js) method that exposes modules on target, registers them if needed and binds all actions given the reactor. Exposed modules are accessible under `<name>Actions` and `<name>Getters`. [Real world example using this](https://github.com/balloob/home-assistant-js/blob/master/src/index.js#L62-L78).

```javascript
import notification from './modules/notification';

const reactor = new Reactor({ debug: true });
var target = {};

exposeModule(target, reactor, {
  notification
});

// You can now access
target.notificationActions.notify({ type: 'success', text: 'Success!' })
Reactor.observe(target.notificaionGetters.notifications, notifs => console.log(notifs));
```

Extra bonus from having modules not depend on a global reactor is that you are able to do server-side rendering too, if desired.

**Comment by raulmatei** [comment]
@balloob wow! 

I have also tried a different and maybe similar approach [here](https://github.com/raulmatei/nuclear-js-test/tree/feature/create-store), not sure if it's a good idea to abstract how stores are created and use a convention which makes you name store handlers as event names (e.g. `ADD_TO_CART -> addToCart(...)`) but I'm playing with it and maybe its another example on how to use NuclearJS.

**Comment by balloob** [comment]
@raulmatei: I use Polymer as one would use React: a declarative API to express my UI. Added value is that Polymer contains UI components implemented by Google, making sure they follow guide lines, accessibility and responsiveness.

**Comment by iansinnott** [comment]
@raulmatei @balloob Thank you both for the suggestions and examples. I'll try out something like these approaches for my current projects

**Comment by iansinnott** [comment]
Going to go ahead and close this out. In addition to the examples above there now seems to be an example of this in the [Iso Chat example](https://github.com/optimizely/nuclear-js/blob/master/examples/isomorphic-flux-chat/client.js#L13).
