### ISSUE TITLE
Is it possible to use ReactMixin with ECMA6 class extension syntax?

### ISSUE THREAD

**Issue by eysi09** [optimizely/nuclear-js#198]
Hi all,

I'm using ES6 class extension syntax to create React components, that is `class MyComponent extends React.Component {}` rather than `React.createClass({})`.

However, I'm having problems when using the Reactor.ReactMixin since it seems to call `getInitialState()` on the component whereas the ES6 react components use the `constructor`method instead. Is there a way around this or will I have to stick `React.createClass`?

**Comment by raulmatei** [comment]
Hi,

See [NuclearJS React addons](https://github.com/jordangarcia/nuclear-js-react-addons), which has nuclearReactor high-order component that uses ReactMixin to get the data bindings and then passes the data down as props to the wrapped component.

Raul.

**Comment by eysi09** [comment]
Hi Raul. 

Thanks for your reply. It seems that method will do the trick. 

-Eysi.

**Comment by raulmatei** [comment]
You're welcome.
