### ISSUE TITLE
Data Bindings as Props instead of State

### ISSUE THREAD

**Issue by gf3** [optimizely/nuclear-js#199]
Earlier I was running into some issues where I wanted to update some state in response to a data binding change however this difficult to do cleanly in React. It got me thinking that perhaps data bindings would be better suited as props on a component vs. state; especially given the immutable nature of nuclear-js. I think it also makes sense in that the components don't really own the data bindings they're connected to and can't explicitly update them anyway. Thoughts on this approach? I'd be happy to take a stab at this over the break if you guys think it has merit.

**Comment by raulmatei** [comment]
Hi,

Probably you're using ReactMixin, see [NuclearJS React Addons and nuclearComponent HoC](https://github.com/jordangarcia/nuclear-js-react-addons#nuclearcomponent), it passes the data bindings as props to the child component.

Raul.

**Comment by gf3** [comment]
Ahh, very nice, thank you.

**Comment by raulmatei** [comment]
You're welcome.
