### ISSUE TITLE
Upgrade Immutable to the latest version

### ISSUE THREAD

**Issue by andrei-cacio** [optimizely/nuclear-js#218]
As of version [3.7.6](https://github.com/facebook/immutable-js/releases/tag/3.7.6) there are new APIs introduced,  like the `insert()` method on `Lists`s.

**Comment by raulmatei** [comment]
This should be fixed by https://github.com/optimizely/nuclear-js/pull/214, which removes the ImmutableJS dependency and adds it as a peer dependency. It will be then the developer's choice on which version to install (the minimum version is 3.7.3, which is the current version used by NuclearJS)

**Comment by andrei-cacio** [comment]
Thanks @raulmatei.  #214 is a better fix for this problem
