### ISSUE TITLE
Disable Dispatch logs using debug packages

### ISSUE THREAD

**Issue by HosseinAgha** [optimizely/nuclear-js#231]
The current way of disabling logs is not standard.
npm libraries usually use [debug](https://www.npmjs.com/package/debug) to log things so when everybody wants to disable them he can do that without altering the package itself.  
Can you use `debug` for logging so we can disable logs?

**Comment by jackschlotthauer-optimizely** [comment]
Would the config object we send to nuclearJS do the job?

From the API:
**Nuclear.Reactor**
```
var reactor = new Nuclear.Reactor(config)
// or
var reactor = Nuclear.Reactor(config)
```

**Configuration Options**
config.debug Boolean - if true it will log the entire app state for every dispatch.

**Comment by HosseinAgha** [comment]
As I said it's not a standard. npm packages mostly use `debug` for this purpose.

**Comment by jackschlotthauer-optimizely** [comment]
@HosseinAgha 

A few thoughts:

Not everyone will use nuclearJS in a build (eg npm/node), we show some folks shipping a pre-built bundle and just including a minified version in their website. In that case, debugging via the console is (almost) the only way. So whichever approach we come to, it should be universal.

You are right to bring this up and it looks like there are a few approaches to solving this: https://www.codementor.io/mattgoldspink/nodejs-best-practices-du1086jja#11-use-a-logging-library-to-increase-errors-visibility

Would you be willing to submit a revision for code review? Right now, this is a low priority at Optimizely, but we'd be willing to consider a revision that supports this.
