### ISSUE TITLE
Use clearer variables names in the example

### ISSUE THREAD

**Issue by appsforartists** [optimizely/nuclear-js#30]
In [the example](https://github.com/optimizely/nuclear-js/#back-to-our-example), the `taxPercent` store is setup thusly:

    this.on('setTaxPercent', function(percent, value) {
      return value
    })

`percent` is a confusing name, since presumably both values are percentages.  Since this is an example, clarity is especially important.  I suggest `state` and `payload`, to maintain the convention used throughout the rest of the document.  `oldPercent` and `newPercent` would also be good choices.

**Comment by appsforartists** [comment]
Similarly, `getTotal` should be called `totalGetter`, to match the preceding section:

```javascript
var over100Getter = [
  getTotal,
  function(total) {
    return total > 100
  }
]

reactor.observe(over100Getter, function(isOver100) {
  if (isOver100) {
    alert('Shopping cart over 100!')
  }
})
```

**Comment by appsforartists** [comment]
And this should be `reactor.ReactMixin`:

```
var React = require('react')

var ShoppingCart = React.createClass({
  mixins: [react.ReactMixin],
```

**Comment by appsforartists** [comment]
syncronously should be synchronously.

**Comment by appsforartists** [comment]
Utilties should be Utilities

**Comment by jordangarcia** [comment]
Hi!

Thanks for suggesting these changes.  Feel free to open a PR and I will gladly merge.

Otherwise I will make these changes later this week.
