### ISSUE TITLE
Create a Gitter room

### ISSUE THREAD

**Issue by appsforartists** [optimizely/nuclear-js#34]
Many of the tools in the React ecosystem have a real-time chat room for their users (and perhaps developers) to discuss best practices and plan for future versions.  Gitter is a nice way to provide this, because it's hosted and well-integrated with GitHub.

@jordangarcia should be able to create a room by [following this link](https://gitter.im/appsforartists/Ambidex#createreporoom).

**Comment by keeth** [comment]
:+1:

**Comment by jordangarcia** [comment]
https://gitter.im/optimizely/nuclear-js :+1: 

Thanks for the link!  I will be in the room during the weekdays, feel free to hop in and ask questions or give suggestions about NuclearJS.
