### ISSUE TITLE
Rerendering and async workflow

### ISSUE THREAD

**Issue by emmenko** [optimizely/nuclear-js#5]
Hi @jordangarcia 

I'm currently learning React and the Flux architecture and came to your library when researching how to use Stores with Immutables. I've stumbled upon a couple of problems / questions though when applying it to my example, so let me explain a bit what I did.

In my example I want to fetch some data from an API when the component is rendered. In the ideal scenario with a Flux architecture it would look like this:

- Component will render
- Component asks state from Store
- Store provides default state to component and triggers an Action to fetch data from an API
- Component renders with initial state
- Action creator execute async request using some util library
- Action creator processes request and if successful will dispatch payload
- Store handles dispatched payload and updates its (immutable) state
- Store informs Component that it has a new state
- Component rerender with new state

Now, when I implement this flow using the `Reactor` the last step is not executed, which could be the same problem @ArnoBuschmann is having https://github.com/optimizely/nuclear-js/issues/4

**Comment by madebyherzblut** [comment]
Wow thanks for the detailed answer @jordangarcia!

**Comment by emmenko** [comment]
@jordangarcia thanks for the explanation :)

**Comment by tomconroy** [comment]
The question about using `.toJS()` this is fixed in React facebook/react#2376
