### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by jordangarcia** [optimizely/nuclear-js#60]
- [x] add instructions to setup repo and testing
- [x] add section for code style
- [x] add part about NOT checking in dist code

I personally like [Vue's CONTRIBUTING.md](https://github.com/yyx990803/vue/blob/master/CONTRIBUTING.md)

@bhamodi would you mind doing?

**Comment by bhamodi** [comment]
Ya, I'll take on this task. :+1:

**Comment by bhamodi** [comment]
Addressed in #62!
