### ISSUE TITLE
Why the utilities?

### ISSUE THREAD

**Issue by jtremback** [optimizely/nuclear-js#70]
Seems like a strange thing to put in a frontend framework. Why not use the utilities in Immutable.js, or at least split these out?

**Comment by jordangarcia** [comment]
Utilities exists to drop the hard dependency on lodash. 

I was / am unaware that immutable.js had the same utiltities.  We use the `utils` when we are dealing with non ImmutableJS data.

**Comment by gaearon** [comment]
Do you really need to *drop* the dependency on lodash? You can import individual functions as modules:

```js
import clone from 'lodash/object/clone';
```

This way, if the consumer *already* uses lodash, they'll have even less code.
