### ISSUE TITLE
NPM's nuclear-js contains an incomplete rest-api-example... (react-native compatibility)

### ISSUE THREAD

**Issue by jtremback** [optimizely/nuclear-js#73]
...with checked-in node_modules, which seem to break react-native. It's react native's fault that they are getting tripped up on an example folder, but I thought you might want to make sure that the latest nuclear-js is up on NPM.

**Comment by jtremback** [comment]
https://github.com/facebook/react-native/issues/1437

**Comment by jtremback** [comment]
This is not an enhancement, and the only person who can help is someone with push access to the NPM module.

**Comment by jordangarcia** [comment]
Fixed in 1.0.5
