### ISSUE TITLE
module name "nuclear-js" vs "nuclearjs"

### ISSUE THREAD

**Issue by alexmcmillan** [optimizely/nuclear-js#84]
I just spent ages wondering why my installation wasn't working before realising I had used `npm install nuclearjs` which is a completely different thing. /facepalm

Is it perhaps worth putting a note in the readme highlighting this is *not* the package named "nuclearjs" on npm?

**Comment by jtremback** [comment]
Possibly a spelling change to bring it into line with the correct pronunciation: `nucular-js`

**Comment by alexmcmillan** [comment]
As a tribute to [this guy](https://www.youtube.com/watch?v=Gpd9AtjWHTg)?

**Comment by bhamodi** [comment]
Well, I'm not sure how to be more clear than [this](https://github.com/optimizely/nuclear-js#installation) haha. Feel free to send a PR if you have a better idea.

**Comment by jtremback** [comment]
![image](https://cloud.githubusercontent.com/assets/1335122/8010305/03736866-0b64-11e5-8ff1-62630fa73543.png)

> "We cannot allow Saddam Hussein to acquire `nucularjs`"

**Comment by alexmcmillan** [comment]
@bhamodi I was just suggesting something like a "not to be confused with nuclearjs" footnote near that line.  My bad.
