### ISSUE TITLE
As of 1.0.5 the [observe example] loop infinite if Store's init data is Infinity value

### ISSUE THREAD

**Issue by singggum3b** [optimizely/nuclear-js#85]
```js
    var budgetStore = Nuclear.Store({
	getInitialState: function() {
		return Infinity;
	},
	initialize: function() {
		this.on('setBudget', function(currentBudget, newBudget) {
			return newBudget
		});
	}
    });
    reactor.registerStores({
	budget: budgetStore
    });

    var isOverBudget = [
	totalGetter,
	['budget'],
	function(total, budget) {
		return total > budget
	}
    ];
    reactor.observe(isOverBudget, function(isOver) {
	// this will be automatically re-evaluated only when the total or budget changes
	if (isOver) {
		var budget = reactor.evaluate(['budget']);
		console.log('Is over budget of ' + budget);
	}
    });

    //this will cause infinite loop
    reactor.dispatch('setBudget', 4);
```

**Comment by singggum3b** [comment]
The issue come from the line  [while (o > 0xFFFFFFFF)] in Hash.js of immutablejs library.
Not sure how much's this related to Nuclearjs.

**Comment by jordangarcia** [comment]
hmmm, I will have to take a look at this.  May be a weird issue in Immutable or it may be how the evaluator is using immutable js with `Infinity`

Also did this happen as of `1.0.5`, ie was this working in `1.0.2`

**Comment by singggum3b** [comment]
Just happen when i try to play with NuclearJS. It's strange that's the readme example having bug.
Could be because it's trying to hash infinity value

**Comment by bhamodi** [comment]
@singggum3b - can you still reproduce this with the latest version? [(v1.1.1)](https://www.npmjs.com/package/nuclear-js)

**Comment by bhamodi** [comment]
Closing for the time being unless we get reports that this is still reproducible.
