### ISSUE TITLE
reactor#unobserve

### ISSUE THREAD

**Issue by colindresj** [optimizely/nuclear-js#87]
Would it make sense to allow a reactor instance's change observer to remove a handler? I think that would be a bit cleaner than saving reference to the observer's unwatch function and calling that at some point

**Comment by jordangarcia** [comment]
Would it be by reference of the handler or the getter?

**Comment by colindresj** [comment]
I was thinking with no arguments removes all handlers, and specific handlers can be removed by providing combinations of getters and handler function names.

```js
reactor.unobserve() // no more observations for the entire reactor instance
reactor.unobserve(['some', 'keypath']) // no more observations on keypath changes
reactor.unobserve(someGetter) // no more observations on getter and/or ancestor changes
reactor.unobserve(someGetter, myHandler) // no more calls to myHandler 
```

**Comment by jordangarcia** [comment]
the api seems pretty sane.  I dont quite see the use case for doing a complete `reactor.unobserve` where you wouldn't want to do an entire `reactor.reset()`

I could see the use for using it by `getter` or `getter` + `handler`.  Have you been running into cases where you find yourself wanting this functionality?

**Comment by colindresj** [comment]
Fair point on `reset`. I can't think of a use case for unobserving without reseting either.

For the most part we've limited our overall use of `observe`, preferring to do things through actions. However, we do have a logging module and an analytics module, and those use `observe` to do things based on app state changes.

It's not often, but sometimes, state changes in a way that means we don't want to (permissions, etc.) log/track anymore. In these case we perform cleanup of observers by keeping a set of maps, each with a mapping to the unwatch function, then looping over the set. Being able to call `unobserve` on a particular keypath or getter, would be more terse and elegant IMO.

**Comment by jordangarcia** [comment]
@colindresj I am pretty busy with the NuclearJS doc sites.  If you want to implement this functionality you are more than welcome to.

**Comment by colindresj** [comment]
Cool, I'll get a PR ready for this soon. Let me know if you need help on the docs site — would be happy to help.

**Comment by jordangarcia** [comment]
@colindresj - would love help on the docs site. lets chat soon

**Comment by jordangarcia** [comment]
Also doing everything in react + Nuclear, been really fun so far.

**Comment by rattrayalex** [comment]
I'm also interested in helping with the docs. Finally have started being able to use Nuclear at work =)

**Comment by bhamodi** [comment]
Done in v1.2.0.
