### ISSUE TITLE
Incompatible implementations of Immutable?

### ISSUE THREAD

**Issue by clessg** [optimizely/nuclear-js#88]
This works:

    import {Immutable} from 'nuclear-js';
    const List = Immutable.List;
   
    class CommentList extends React.Component {
      static propTypes = {
        comments: React.PropTypes.instanceOf(List).isRequired
      }
    }

But this does not:

    import {List} from 'immutable';
   
    class CommentList extends React.Component {
      static propTypes = {
        comments: React.PropTypes.instanceOf(List).isRequired
      }
    }

Warning:

    Failed propType: Invalid prop `comments` supplied to `CommentList`, expected instance of `List`. Check the render method of `UpdatePage`.

Is that supposed to happen? I'm using Webpack, nuclear-js 1.0.5, and immutable 3.7.3.

**Comment by jordangarcia** [comment]
It could be that there are two instances of Immutable in your build since one is bundled in with Nuclear.

One way to get around this would be to alias `'immutable'` to use the NuclearJS version in webpack.

**Comment by clessg** [comment]
I looked at the app's full build file and it is indeed being included twice. One is a dependency of my own app, while the other is a dependency of NuclearJS. Both are 3.7.3. Interestingly though, the version bundled with Nuclear appears to be somewhat outdated. I assume this is because the `dist/nuclear.js` file includes its own version of Immutable.

Thus, if you own app includes Immutable, Immutable will always be bundled twice, as far as I can tell. My apologies if any of this is wrong, it's really late.

Is there any particular reason to reference the `dist/nuclear.js` file rather than, say, `src/main.js`?

**Comment by jordangarcia** [comment]
The reason is that nuclear was written in es6, and to be compatible with node / non-transpiled we are pointing the entry point to the built dist file.

If you are using webpack + an es6 transpiler then you can alias `nuclear-js` directly to `node_modules/nuclear-js/src/main.js`

I agree that this is less than ideal.  Perhaps a better solution would be to point to an es5 version of source files without concatenation.

**Comment by clessg** [comment]
Ah yes, that makes sense. Thank you.
