### ISSUE TITLE
Uncaught (in promise) TypeError: Illegal invocation

### ISSUE THREAD

**Issue by jtremback** [optimizely/nuclear-js#92]
Getting this at line 46 of `change-observer.js`.

In Firefox the error is `Unhandled promise rejection" TypeError: 'log' called on an object that does not implement interface Console`

I'm using Babel as well, maybe this has something to do with it.

**Comment by jtremback** [comment]
Here's the project this is happening with: https://github.com/jtremback/flux-comparison/tree/master/nuclear/js

**Comment by jordangarcia** [comment]
hm, is it happening immediately when the app is run, or after some action?

**Comment by jtremback** [comment]
It happens after an action

**Comment by jordangarcia** [comment]
This is the culprit: https://github.com/jtremback/flux-comparison/blob/master/nuclear/js/components/ProductsContainer.jsx#L30

`flux.observe(['products'], console.log);`

By passing `console.log` as the handler its losing the `console` `this` context.

`flux.observe(['products'], products => console.log(products))`

and for sake of logging it probably needs a toJS

```
import { toJS } from 'nuclear-js'

`flux.observe(['products'], products => console.log(products))`
```

**Comment by jtremback** [comment]
Ooops! Thanks.
