### ISSUE TITLE
Consider using Cursors into the immtuable map.

### ISSUE THREAD

**Issue by Tritlo** [optimizely/nuclear-js#95]
Have you considered using [cursors](https://github.com/facebook/immutable-js/tree/master/contrib/cursor) into the Immutable? It might simplify things a lot, and even give a performance boost.

**Comment by jordangarcia** [comment]
hey @Tritlo.  Can you be more specific?  Are you referring to giving out cursors to components or using cursors as the implementation of observables?

**Comment by Tritlo** [comment]
Using as the implementation. It seems to me that it would be cleaner to use Immutables built in facilities, but I admit that I have not looked into this thoroughly. Is there a specific reason that you do not, or would you be open to review a pull request of an observables implementation with cursors at a later time?

**Comment by rattrayalex** [comment]
Last I checked Cursors were experimental/unmaintained at Immutable. 

...(checks)...
... yep: https://github.com/facebook/immutable-js/issues/363

**Comment by Tritlo** [comment]
It seemed  a bit weird that your were re-implementing built-in functionality, but that explains it. Thank you fro the clarification.
