### ISSUE TITLE
NuclearJS docs link gets redirected away.

### ISSUE THREAD

**Issue by bhamodi** [optimizely/nuclear-js#96]
http://developers.optimizely.com/nuclear-js/docs/ redirects to http://developers.optimizely.com/
Could this be due to the recent update to the dev docs @jordangarcia ?

**Comment by jordangarcia** [comment]
yeah, its redirecting to `/` and it should be `'nuclear-js'`  I will fix
soon

however developers.optimizely.com/nuclear-js works

**Comment by bhamodi** [comment]
Oh nice, are we moving the landing page to `/nuclear-js`?

**Comment by jordangarcia** [comment]
fixed

**Comment by citelao** [comment]
http://developers.optimizely.com/nuclear-js does not load for me
