### ISSUE TITLE
Help: pattern for writing getters depending on state that might be null 

### ISSUE THREAD

**Issue by tonytamps** [optimizely/nuclear-js#98]
I'm having a bit of trouble developing a pattern to handle `getters` with a dependency on some app state that may be null. See the getters bellow:
```javascript
// getters.js
exports.org = ['org'];
exports.menus = ['menus'];
exports.selectedMenu = [exports.org, exports.menus, (org, menus) =>
  menus.find(menu => menu.get('id') === org.get('default_menu'))
];
```

If `org` and `menus` are both defined, this is fine. But it may be possible for them to be undefined, which would cause a `.get()` of undefined.

I know I can code defensively in computed properties to return a reasonable value if they are undefined but this feels like a bad pattern to adapt everywhere.

I believe part of the problem I'm having is that when `getDataBindings` returns an object (like below) it 'pulls' on the computed properties attempting to get a value

```javascript
// menu.jsx - requires the getters.js
module.exports = React.createClass({
  mixins: [flux.ReactMixin],

  getDataBindings: function() {
    return {
      menus: Session.getters.menus,
      selectedMenu: Session.getters.selectedMenu,
    };
  },

  render() { ... }
});
```

I'm assuming that you have a pattern to avoid loading the `menu.jsx` component if the data required for it hasn't been populated yet? Do you just `return false` in the parent component's `render()` if the data isn't there? Am I making any sense?

**Comment by jordangarcia** [comment]
Hi @tonytamps 

What you are going through can happen when programming using reactively, you need to make sure all of the cases that are possible are handled.

While I agree getting in a pattern of defensive coding isn't ideal there are times where we need to be defensive or at least have a sensible default.

In your case, it looks like `menus` should always be a List or Map even if its empty.  One way to go about it would be:

```js
exports.org = ['org'];
exports.menus = [
  ['menus'],
  (menus) => menus || toImmutable([])
];
exports.selectedMenu = [exports.org, exports.menus, (org, menus) =>
  menus.find(menu => menu.get('id') === org.get('default_menu'))
];
```

While this solution does require you to be defensive, it ensures that anything you build on top of the `menus` getter is getting the same type back, an `Immutable.List`.  This is a good compromise of being defensive while not letting the defensive pattern leak down into getters that are consuming `menus`

Hope this helps!  Let me know if you have any other questions.

**Comment by tonytamps** [comment]
So my problem might be that a lot of my getters are just `exports.getterName = ['propName'] which means I have to be defensive downstream. 

I'm still a little concerned about the `render` function being overly defensive but I'll see how this change impacts it. 

Do you favor the parent not rendering the child if the data isn't available, or the child not rendering itself if the data isn't available? I'm assuming the latter.

**Comment by jordangarcia** [comment]
I would say that the parent should generally be responsible for choosing whether to render a child or not, based on the state of your application.  

Keep in mind there is a difference between a value explicitly being null, in your case if there is no menu selected and the value being `null` or `undefined` because it relies on data that isn't available.

**Comment by rattrayalex** [comment]
@tonytamps I'm curious, why wouldn't your store be responsible for returning the empty `Immutable.List([])` when no data is available? `null` seems like a clearly anti-useful return type for your application. 

If you're going through the trouble of defining getters for all the keypaths you use (I usually just use keypaths directly, but like your approach now that I see it), what would be wrong with @jordangarcia 's recommendation of casting to a default in the data's getter?

**Comment by tonytamps** [comment]
> I'm curious, why wouldn't your store be responsible for returning the empty `Immutable.List([])`
It can! Sometimes it is. In this case it wasn't. I still don't have a strong reason to go either way but I'm leading towards this (using the store) because of the way it keeps the getters clean.

> `null` seems like an un-useful return type for your application.
Totally agree. It was the crux of the problem.

> what would be wrong with @jordangarcia 's recommendation of casting to a default in the data's getter 
Nothing wrong, its actually correct and still required sometimes even when your store has been returning default data. Usually when you have a complex object and some of the getters are attempting to access child properties.

> I'm also +1 for the parent generally being responsible for deciding whether or not to render the child.
Jury is still out on this. For now I'm putting it where the code is simplest.

I'll close the issue because I believe I have all the help I need. Thanks :grinning:
