### ISSUE TITLE
Initial data loading

### ISSUE THREAD

**Issue by raulmatei** [optimizely/nuclear-js#99]
Is there any functionality available to setup stores with some initial data, stored in a global variable or passed as a parameter to an App.initialize(spec) method. I've seen on other Flux implementations that have similar behavior, e.g.: 

```
Flux.start({
  StoreName: { /* store data */ },
  OtherStore: { /* store data */ }
});
```

Raul.

**Comment by jordangarcia** [comment]
Hi Raul,

Right now there isn't a generic way to load the entire app state.  The pattern we've used to do this is to create an action for the event of loading initial data and then having individual stores choose to handle it.

```js
flux.dispatch(actionTypes.LOAD_INITIAL_DATA, data);
```

and in your stores:

```js
Store({
  getInitialState() {
    toImmutable({});
  },
  initialize() {
    this.on(actionTypes.LOAD_INITIAL_STATE, loadState)
  },
});

function loadState(state, payload) {
  // the store has the option here to do a transform over the initial data
  return toImmutable(payload.users);
}
```

**Comment by raulmatei** [comment]
Thanks Jordan,

That's what I'm using, but it looks to me that if the application grows and more stores will need data on page load, I'll have to make sure that each of these stores listen to this event and also implement a pure function that will pick and maybe transform the needed data.

Raul.

**Comment by jordangarcia** [comment]
Yep, thats the general pattern. In my eyes you will have to do that anyways unless your source of truth from the server is the same Nuclear.Reactor for isomorphic data (there are plans to better support this in 1.1)

For now you can do something like this:

```js
class InjectableReactor extends Nuclear.Reactor {
  loadState(state) {
    this.__state = state;
  }
}
```

and in your startup script:

```js
var reactor = new InjectableReactor();

// register stores
reactor.registerStores({
  StoreName: require('./stores/StoreName.js'),
  OtherStore: require('./stores/OtherStore.js'),
});

reactor.loadState(toImmutable({
  StoreName: { /* store data */ },
  OtherStore: { /* store data */ }
});
```

**Comment by raulmatei** [comment]
I'll use the actions flow for now. But I'm still interested to make it work automatically (or magically) without updating the entire app state but individual stores, in your example if you try to inject only one store in the current state, it will delete all other stores:

```
// register stores
reactor.registerStores({
  auth: require('./stores/auth.js'),
  posts: require('./stores/posts.js'),
  profile: require('./stores/profile.js')
});

// loading just the posts store, will delete auth and profile, even if they are empty, they are gone
reactor.loadState(toImmutable({
  posts: { /* store data */ }
});
```

And as you said above, it forces me to always inject the entire app state.

Thanks,
Raul.
